DROP TABLE VOLUNTEERING CASCADE CONSTRAINTS;

CREATE TABLE VOLUNTEERING(
	vid int,
	vplace varchar2(20),
	vdate date,
	vsalary number,
	oid int,
	tid int,
	--primary key(vid),
	FOREIGN KEY(oid) REFERENCES ORGANIZATION(oid),
	FOREIGN KEY(tid) REFERENCES TEAMS(tid));

    INSERT INTO VOLUNTEERING(VID,VPLACE,VDATE,VSALARY,OID,TID)
	SELECT VID,VPLACE,VDATE,VSALARY,OID,TID
	FROM 
	(SELECT * FROM 
	VOLUNTEERING1
	UNION ALL 
	SELECT * FROM VOLUNTEERING2 @SITE1 V2);
	
COMMIT;
